### ISSUE TITLE
Gollumn 0.9.9 SDK crash

### ISSUE THREAD

**Issue by LSDsl** [ComThings/PandwaRF#53]
`java.lang.NoClassDefFoundError: Failed resolution of: Lio/fabric/sdk/android/Fabric;
                      at com.comthings.gollum.api.gollumandroidlib.GollumFirebase.log(GollumFirebase.java:120)
                      at com.comthings.gollum.api.gollumandroidlib.utils.Utils.log(Utils.java:43)
                      at com.comthings.gollum.api.gollumandroidlib.GollumDongle.<init>(GollumDongle.java:50278)
                      at com.comthings.gollum.api.gollumandroidlib.GollumDongle.getInstance(GollumDongle.java:691)`

**Comment by trollwookiee** [comment]
Fabric is now disabled in SDK builds.

Can you please check with 82b4130 and 'com.comthings.pandwarf:gollum:0.9.9' ?
Thanks
