### ISSUE TITLE
Crash during updateFirmwareCC1111 [SDK 0.9.12]

### ISSUE THREAD

**Issue by LSDsl** [ComThings/PandwaRF#61]
Crash during [updateFirmwareCC1111 ](https://comthings.github.io/PandwaRF/v0.9.12/com/comthings/gollum/api/gollumandroidlib/GollumDongle.html#updateFirmwareCC1111-java.lang.String-com.comthings.gollum.api.gollumandroidlib.callback.GollumCallback-com.comthings.gollum.api.gollumandroidlib.callback.GollumCallbackGetInteger-com.comthings.gollum.api.gollumandroidlib.callback.GollumCallbackGetProgressStatus-com.comthings.gollum.api.gollumandroidlib.callback.GollumCallbackGetInteger-)

```
 java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.firebase.analytics.FirebaseAnalytics.logEvent(java.lang.String, android.os.Bundle)' on a null object reference
                      at com.comthings.gollum.api.gollumandroidlib.GollumFirebase.logUpdateFwEvent(GollumFirebase.java:217)
                      at com.comthings.gollum.api.gollumandroidlib.HandleFirmwareCC1111$a.onPostExecute(HandleFirmwareCC1111.java:2792)
                      at android.os.AsyncTask.finish(AsyncTask.java:636)
                      at android.os.AsyncTask.access$500(AsyncTask.java:177)
                      at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:211)
                      at android.app.ActivityThread.main(ActivityThread.java:5371)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:945)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:740)
```

**Comment by trollwookiee** [comment]
Fixed, will be dispatched soon.
